version: "2"
services:
  registry:
    container_name: class_registry
    image: registry:2.6.2
    restart: unless-stopped
    networks:
      - my-net
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/domain.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/domain.key"
      REGISTRY_HTTP_SECRET: "iuehfio73bt8dobq"
    volumes:
     - "./files/config.yml:/etc/docker/registry/config.yml"
     - "./files/htpasswd:/htpasswd"
     - "./data:/var/lib/registry"
     - "./certs:/certs"
networks:
  my-net:
    driver: bridge
